stateDiagram-v2
    [*] --> ApplicationStop
    ApplicationStop --> DownloadBundle
    DownloadBundle --> BeforeInstall
    BeforeInstall --> Install
    Install --> AfterInstall
    AfterInstall --> ApplicationStart
    ApplicationStart --> ValidateService
    ValidateService --> [*]
